apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-09-18T10:19:52Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "192"
  uid: f876138d-556d-4560-a294-ca2e84434afe
spec:
  clusterIP: 10.119.128.1
  clusterIPs:
  - 10.119.128.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
