apiVersion: v1
kind: Node
metadata:
  annotations:
    container.googleapis.com/instance_id: "7979751108256308574"
    csi.volume.kubernetes.io/nodeid: '{"filestore.csi.storage.gke.io":"gk3-europe-west1-osm-to--default-pool-9f14752d-98fq","gcsfuse.csi.storage.gke.io":"gk3-europe-west1-osm-to--default-pool-9f14752d-98fq","pd.csi.storage.gke.io":"projects/huq-jimbo/zones/europe-west1-b/instances/gk3-europe-west1-osm-to--default-pool-9f14752d-98fq"}'
    node.alpha.kubernetes.io/ttl: "0"
    node.gke.io/last-applied-node-labels: addon.gke.io/node-local-dns-ds-ready=true,cloud.google.com/gke-boot-disk=pd-standard,cloud.google.com/gke-container-runtime=containerd,cloud.google.com/gke-cpu-scaling-level=2,cloud.google.com/gke-gcfs=true,cloud.google.com/gke-image-streaming=true,cloud.google.com/gke-logging-variant=DEFAULT,cloud.google.com/gke-max-pods-per-node=32,cloud.google.com/gke-netd-ready=true,cloud.google.com/gke-nodepool=default-pool,cloud.google.com/gke-os-distribution=cos,cloud.google.com/gke-provisioning=standard,cloud.google.com/gke-stack-type=IPV4,cloud.google.com/machine-family=e2,cloud.google.com/private-node=false,iam.gke.io/gke-metadata-server-enabled=true,node.kubernetes.io/masq-agent-ds-ready=true
    node.gke.io/last-applied-node-taints: ""
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2023-09-18T10:21:14Z"
  labels:
    addon.gke.io/node-local-dns-ds-ready: "true"
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: e2-medium
    beta.kubernetes.io/os: linux
    cloud.google.com/gke-boot-disk: pd-standard
    cloud.google.com/gke-container-runtime: containerd
    cloud.google.com/gke-cpu-scaling-level: "2"
    cloud.google.com/gke-gcfs: "true"
    cloud.google.com/gke-image-streaming: "true"
    cloud.google.com/gke-logging-variant: DEFAULT
    cloud.google.com/gke-max-pods-per-node: "32"
    cloud.google.com/gke-netd-ready: "true"
    cloud.google.com/gke-nodepool: default-pool
    cloud.google.com/gke-os-distribution: cos
    cloud.google.com/gke-provisioning: standard
    cloud.google.com/gke-stack-type: IPV4
    cloud.google.com/machine-family: e2
    cloud.google.com/private-node: "false"
    failure-domain.beta.kubernetes.io/region: europe-west1
    failure-domain.beta.kubernetes.io/zone: europe-west1-b
    iam.gke.io/gke-metadata-server-enabled: "true"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: gk3-europe-west1-osm-to--default-pool-9f14752d-98fq
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: e2-medium
    node.kubernetes.io/masq-agent-ds-ready: "true"
    topology.gke.io/zone: europe-west1-b
    topology.kubernetes.io/region: europe-west1
    topology.kubernetes.io/zone: europe-west1-b
  name: gk3-europe-west1-osm-to--default-pool-9f14752d-98fq
  resourceVersion: "400691"
  uid: afc0a53d-9da5-488b-a0ef-d602c6344165
spec:
  podCIDR: 10.119.0.0/26
  podCIDRs:
  - 10.119.0.0/26
  providerID: gce://huq-jimbo/europe-west1-b/gk3-europe-west1-osm-to--default-pool-9f14752d-98fq
status:
  addresses:
  - address: 10.132.15.212
    type: InternalIP
  - address: 34.77.213.66
    type: ExternalIP
  - address: gk3-europe-west1-osm-to--default-pool-9f14752d-98fq
    type: Hostname
  allocatable:
    cpu: 940m
    ephemeral-storage: "47060071478"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 2836148Ki
    pods: "32"
  capacity:
    cpu: "2"
    ephemeral-storage: 98831908Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 4022964Ki
    pods: "32"
  conditions:
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: docker overlay2 is functioning properly
    reason: NoCorruptDockerOverlay2
    status: "False"
    type: CorruptDockerOverlay2
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: docker is functioning properly
    reason: NoFrequentDockerRestart
    status: "False"
    type: FrequentDockerRestart
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: Gcfsd is functioning properly
    reason: NoFrequentGcfsdRestart
    status: "False"
    type: FrequentGcfsdRestart
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: kubelet is functioning properly
    reason: NoFrequentKubeletRestart
    status: "False"
    type: FrequentKubeletRestart
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: GcfsSnapshotter is functioning properly
    reason: NoFrequentGcfsSnapshotterRestart
    status: "False"
    type: FrequentGcfsSnapshotterRestart
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: GcfsSnapshotter on the node is functioning properly
    reason: GcfsSnapshotterIsHealthy
    status: "False"
    type: GcfsSnapshotterUnhealthy
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: GCFS Snapshotter has no missing layer
    reason: GcfsSnapshotterHasNoMissingLayer
    status: "False"
    type: GcfsSnapshotterMissingLayer
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: node is functioning properly
    reason: NoFrequentUnregisterNetDevice
    status: "False"
    type: FrequentUnregisterNetDevice
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:17Z"
    message: kernel has no deadlock
    reason: KernelHasNoDeadlock
    status: "False"
    type: KernelDeadlock
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:17Z"
    message: Filesystem is not read-only
    reason: FilesystemIsNotReadOnly
    status: "False"
    type: ReadonlyFilesystem
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: Gcfsd on the node is functioning properly
    reason: GcfsdIsHealthy
    status: "False"
    type: GcfsdUnhealthy
  - lastHeartbeatTime: "2023-09-18T16:01:51Z"
    lastTransitionTime: "2023-09-18T10:21:18Z"
    message: containerd is functioning properly
    reason: NoFrequentContainerdRestart
    status: "False"
    type: FrequentContainerdRestart
  - lastHeartbeatTime: "2023-09-18T10:21:14Z"
    lastTransitionTime: "2023-09-18T10:21:14Z"
    message: NodeController create implicit route
    reason: RouteCreated
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2023-09-18T15:59:27Z"
    lastTransitionTime: "2023-09-18T10:18:14Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2023-09-18T15:59:27Z"
    lastTransitionTime: "2023-09-18T10:18:14Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2023-09-18T15:59:27Z"
    lastTransitionTime: "2023-09-18T10:18:14Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2023-09-18T15:59:27Z"
    lastTransitionTime: "2023-09-18T10:21:44Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/airflow-worker-scheduler-2-5-3/airflow-worker-scheduler-2-5-3@sha256:7c2214dc1cb9cbe2f16bf2610be909f4d0baa38b15bd8ca0dae0292c46584310
    - europe-docker.pkg.dev/cloud-airflow-releaser/airflow-worker-scheduler-2-5-3/airflow-worker-scheduler-2-5-3:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 1925560153
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/airflow-monitoring/airflow-monitoring@sha256:538a8464c26ab9e8c10ea64b3700524e2b8c24cbbd2742606f232caf7cdf84b8
    - europe-docker.pkg.dev/cloud-airflow-releaser/airflow-monitoring/airflow-monitoring:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 650869976
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/task-monitor/task-monitor@sha256:2adbbb62e1be80c3905c196f2c3c85384f59f237b0653d9d954831d9f4c487ca
    - europe-docker.pkg.dev/cloud-airflow-releaser/task-monitor/task-monitor:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 643888098
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-agent/composer-agent@sha256:142cc20cc399f0fe2fbbbd24d4470928d528403cbf90dada774796790cd8425f
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-agent/composer-agent:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 641986454
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/gcs-syncd/gcs-syncd@sha256:55b421cc43cd7c08f708cac05eaa20581a1bd98553c1a79ebb8ab8527cccce88
    - europe-docker.pkg.dev/cloud-airflow-releaser/gcs-syncd/gcs-syncd:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 618327390
  - names:
    - gke.gcr.io/cilium/cilium@sha256:69668a1f2e11b3303cb1be8307895181e76c58ac20cc3bedc0f5b3fd6410bb4a
    sizeBytes: 184384894
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/redis/redis-6.2.6@sha256:eec9f8d419e9796419dc2183cd66a20c880b46fdabaa3867599ddb24e8f3f64e
    - europe-docker.pkg.dev/cloud-airflow-releaser/redis/redis-6.2.6:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 161303000
  - names:
    - gke.gcr.io/prometheus-engine/prometheus@sha256:58a2131bd6b9ef640d8d0e1e9902e94659ded2231e9f0deb3be5e06218b67078
    sizeBytes: 134970895
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-fluentd/composer-fluentd@sha256:328994a7eca739a47e1410a838064c54571fb9f61b57a202d76163b3da31184e
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-fluentd/composer-fluentd:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 128929554
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-cloudsql-proxy/composer-cloudsql-proxy@sha256:a6875d3e652d936aa914a28b7de6609e6b19525722369d3e24de73caf7c66b1f
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-cloudsql-proxy/composer-cloudsql-proxy:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 117517915
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-proxy/composer-proxy@sha256:af84dc3d77079a31ffc9a73a8e8e0328a1e66294639c6683b7f57104c7352d5b
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-proxy/composer-proxy:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 103725645
  - names:
    - gke.gcr.io/prometheus-engine/rule-evaluator@sha256:fd9689a56ed3b73c5e7c5e6f820f96301c0a5272ba217304e15d2d4ef7f63011
    sizeBytes: 75069175
  - names:
    - gke.gcr.io/prometheus-engine/operator@sha256:ab86a8fb04a10ac4f34bd2b248766790031abdcea0e50eb86cd983321529ed15
    sizeBytes: 74593706
  - names:
    - gke.gcr.io/gcp-filestore-csi-driver@sha256:3eb2cb6d0f2715893ec3af8c8d2f0f82ff5cc93a8ef1389fcb4def0cf8f90889
    sizeBytes: 71975491
  - names:
    - gke.gcr.io/kube-proxy-amd64:v1.26.7-gke.500
    - k8s.gcr.io/kube-proxy-amd64:v1.26.7-gke.500
    sizeBytes: 67924691
  - names:
    - gke.gcr.io/prometheus-engine/config-reloader@sha256:084025f08e56666404d432fc8f0bdfe4c03f1c11b4ed277cd030818fa7c81c3c
    sizeBytes: 56087555
  - names:
    - gke.gcr.io/gcp-compute-persistent-disk-csi-driver@sha256:c28aa890eb453aeea04990b45f19fd9aa7a51dd11bf333a27f1a047ce658d8c1
    sizeBytes: 53630330
  - names:
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-gcsfuse/composer-gcsfuse@sha256:44dd30712ab46ec6130e01dacdbd1c3bf9a8fd1e21670837fdc723f3742ee4c6
    - europe-docker.pkg.dev/cloud-airflow-releaser/composer-gcsfuse/composer-gcsfuse:cloud_composer_service_2023-09-05-RC1
    sizeBytes: 48655839
  - names:
    - gke.gcr.io/fluent-bit@sha256:c03635e4c828b9c6847df9780d6684b45ff0a70b1ae8c7e7271283cce472085e
    sizeBytes: 45820648
  - names:
    - gke.gcr.io/k8s-dns-node-cache@sha256:88052cde040efad7f40959a301d01bfd5130f36ead4c927880c459cbb93d7066
    sizeBytes: 36275907
  - names:
    - gke.gcr.io/gke-metadata-server@sha256:c64b779853dfa571d5583df91fe77dde18b6e0b465df58077f6422bd8edc99e3
    sizeBytes: 35251597
  - names:
    - gke.gcr.io/prometheus-to-sd@sha256:654791db0d4d17c5847221fd3ace5c23ea1bb20c5976db9fda0853fd6000ab65
    sizeBytes: 34871038
  - names:
    - gke.gcr.io/prometheus-to-sd@sha256:8cd7e6b460418e25f80a4a0e8aa865bd5b716ea8750bfea4f6fc163c9b1c5dbb
    sizeBytes: 34319570
  - names:
    - gke.gcr.io/k8s-dns-dnsmasq-nanny@sha256:d7c0300eee5fb4998d3b60d92e5c07c9c4be2f489e04bdfa1950f2e23eb59bcc
    sizeBytes: 33495311
  - names:
    - gke.gcr.io/fluent-bit-gke-exporter@sha256:93014f5d546376de76c21f48bf30a6d1df3db4a413a1c3009c59fe46fa83eee8
    sizeBytes: 32490866
  nodeInfo:
    architecture: amd64
    bootID: 6082ac7f-3ff1-4c83-8999-5426a20f3afc
    containerRuntimeVersion: containerd://1.6.18
    kernelVersion: 5.15.107+
    kubeProxyVersion: v1.26.7-gke.500
    kubeletVersion: v1.26.7-gke.500
    machineID: 9df95ecb4b0e5a780173c816cca4cccb
    operatingSystem: linux
    osImage: Container-Optimized OS from Google
    systemUUID: 9df95ecb-4b0e-5a78-0173-c816cca4cccb
  volumesAttached:
  - devicePath: ""
    name: kubernetes.io/csi/pd.csi.storage.gke.io^projects/huq-jimbo/zones/europe-west1-b/disks/pvc-f5239f5f-4c11-4972-ac97-20fe2db7e245
  volumesInUse:
  - kubernetes.io/csi/pd.csi.storage.gke.io^projects/huq-jimbo/zones/europe-west1-b/disks/pvc-f5239f5f-4c11-4972-ac97-20fe2db7e245
