apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openstreetmap-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2500Gi
  storageClassName: standard-rwo