kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openstreetmap-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2500Gi
